version: "3"

services:
  api:
    build:
      context: ./api
    container_name: fastapi_container
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - my_network

  streamlit:
    build:
      context: ./streamlit
    container_name: streamlit_container
    env_file:
      - .env
    ports:
      - "8501:8501"
    networks:
      - my_network
    depends_on:
      - api

networks:
  my_network:
    driver: bridge
